name: Check PR
run-name: Check ${{ github.ref_name }} by @${{ github.actor }}

on:
  pull_request:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check code formatting
        run: deno task check:format
      - name: Lint code
        run: deno task check:lint
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install commitlint
        run: |
          npm init -y
          npm pkg set type="module"
          npm install @commitlint/config-conventional @commitlint/cli
          echo "export default {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
      - name: Lint commit messages
        run: npx commitlint --from=$(git rev-parse origin/${{ github.base_ref}}) --to=HEAD
